version: '3.8'

services:
  chromadb-viewer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./database:/app/database
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 